version: '3'
services:
  monolith:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - redis  
  redis:
    image: redis
  celery-beat:
    image: celery
    build: .
    volumes:
      - .:/code
    command: celery -A monolith.background beat -l info
    depends_on:
      - redis
    links:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND_URL=redis://redis:6379/0
      - C_FORCE_ROOT=true
  celery-work:
    image: celery
    build: .
    volumes:
      - .:/code
    command: celery -A monolith.background worker -l info
    depends_on:
      - redis
      - celery-beat
    links:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND_URL=redis://redis:6379/0
      - C_FORCE_ROOT=true          
    

 